### ISSUE TITLE
[feature request] 开发环境需要 CORS header

### ISSUE THREAD

**Issue by FrankFang** [hcsp/wxshop#3]
在 dev 环境开启 server 时，如果所有请求都能带上一个 `Access-Control-Allow-Origin: localhost:3000` 那么前端开发就会更方便了。

**Comment by blindpirate** [comment]
Fixed in https://github.com/hcsp/wxshop/commit/da569c20cf3e64cfc71a626d0b9eb3e6abd6ba24

**Comment by FrankFang** [comment]
纠正，应该是 `Access-Control-Allow-Origin: http://localhost:3000`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Examples
